/*Creacion de tablas*/

CREATE TABLE PRODUCTO (
	ID INT IDENTITY(1,1) PRIMARY KEY,
	ESPECTACULO VARCHAR(4000),
	FECHA_ESPECTACULO DATETIME,
	CIUDAD_ESPECTACULO VARCHAR(4000),
	FECHA_LLEGADA DATETIME,
	FECHA_SALIDA DATETIME,
	TIPO_TRANSPORTE INT ,
	TIPO_ESPECTACULO INT,
	TIPO_OSPEDAJE INT
)


CREATE TABLE TARIFA_HOSPEDAJE (
	ID INT IDENTITY(1,1) PRIMARY KEY,
	NOMBRE_TIPO VARCHAR(4000),
	PRECIO DECIMAL
)


CREATE TABLE TARIFA_CIUDAD (
	ID INT IDENTITY(1,1) PRIMARY KEY,
	NOMBRE_TIPO VARCHAR(4000),
	PRECIO DECIMAL
)


CREATE TABLE TARIFA_TRANSPORTE (
	ID INT IDENTITY(1,1) PRIMARY KEY,
	NOMBRE_TIPO VARCHAR(4000),
	PRECIO DECIMAL
)


CREATE TABLE TARIFA_ESPECTACULO (
	ID INT IDENTITY(1,1) PRIMARY KEY,
	NOMBRE_TIPO VARCHAR(4000),
	PRECIO DECIMAL
)



CREATE TABLE CIUDAD (
	ID_CIUDAD VARCHAR(500) PRIMARY KEY,
	PAIS VARCHAR(4000),
	TIPO_CIUDAD INT
)


/* Insercion data inicial */

INSERT INTO PRODUCTO VALUES ('Clasico tolima', getdate(),'Bogotá D.C.', getdate(), getdate(),1,1,1)

INSERT INTO TARIFA_HOSPEDAJE VALUES ('Hotel', 1200000)

INSERT INTO TARIFA_CIUDAD VALUES ('CRUCERO BOGOTA', 7000000)

INSERT INTO TARIFA_TRANSPORTE VALUES ('AVION',400000)

INSERT INTO TARIFA_ESPECTACULO VALUES ('CRUCERO POR EL RIO BOGOTA', 5000000)

INSERT INTO CIUDAD VALUES ('Bogotá D.C.', 'Colombia', 1)

/* Consultas
	
	select * from TARIFA_HOSPEDAJE
	select * from TARIFA_CIUDAD
	select * from TARIFA_TRANSPORTE
	select * from TARIFA_ESPECTACULO
	select * from CIUDAD

*/


